- id: ignition-lint
  name: Ignition Lint
  description: "Lints Ignition Perspectve JSON files for style consistency"
  entry: ignition-lint 
  language: python
  language_version: python3
  types: [json]
  files: view\.json$
  pass_filenames: true
  additional_dependencies: []