repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        args:
          - "--rcfile=.pylintrc"
        types: [python]
        files: ^src/ignition_lint/.*\.py$

      - id: ignition-lint
        name: ignition-lint
        entry: poetry run python src/ignition_lint
        language: system
        args:
          - "--config=.ignition-lint-precommit.json"
          - "--files"
        files: '.*view\.json$'
        types: [json]
        exclude: '^tests/cases/.*'  # Exclude test files that intentionally have violations

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
