- id: ignition-lint
  name: Ignition Lint
  entry: ignition-lint 
  language: python
  types: [json]
  files: view\.json$
  description: "Lints Ignition JSON files for style consistency"
  additional_dependencies: []