repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "--rcfile=.config/.pylintrc",
          "--msg-template=\"{path}({line}): [{obj}] {msg} ({symbol})\"",
        ]

      # - id: markdownlint
      #   name: markdownlint
      #   entry: markdownlint
      #   language: system
      #   types: [markdown]
      #   args: [
      #     "--config=.config/.markdownlint.json",
      #     "--ignore-path=.config/.markdownlintignore"
      #   ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '(resource|view)\.json$'
      - id: check-yaml
      - id: check-added-large-files
