name: "Ignition Lint"
description: "Action to lint ignition view.json files"
author: "Eric Knorr"

inputs:
  files:
    description: "Comma-separated list of files or glob patterns to lint"
    required: false
    default: "**/view.json"
  config:
    description: "Path to configuration JSON file"
    required: false
    default: "rule_config.json"
  verbose:
    description: "Show detailed statistics and information"
    required: false
    default: "false"

branding:
  icon: "zap"
  color: "orange"

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false
      shell: bash
    
    - name: Install dependencies
      run: |
        cd "${{ github.action_path }}"
        poetry install --no-dev
      shell: bash
    
    - name: Lint ignition view.json files
      run: |
        cd "${{ github.action_path }}"
        poetry run ignition-lint \
          --config "${{ inputs.config }}" \
          --files "${{ inputs.files }}" \
          ${{ inputs.verbose == 'true' && '--verbose' || '' }}
      shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_VERBOSE: ${{ inputs.verbose }}
