# Sample workflow demonstrating the ignition-lint GitHub action
# 
# This file serves as both documentation and a test workflow.
# Copy this to .github/workflows/ in your repository to use ignition-lint
# as a GitHub Action on your Ignition projects.
name: Lint Ignition Views
on: 
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Lint Ignition view files
        uses: ./
        with:
          files: "**/view.json"
          config: "rule_config.json" 
          verbose: "false"